export const ADD_ITEM_CART =  'ADD_ITEM_CART'
export const REMOVE_ITEM_CART =  'REMOVE_ITEM_CART'

export const CART_SAVE_COUNTRY_CUSTOMER = 'CART_SAVE_COUNTRY_CUSTOMER'

export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT'
export const CART_NAME_PAYMENT = 'CART_NAME_PAYMENT'

export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART'