export const MY_COURSES_REQUEST = 'MY_COURSES_REQUEST'
export const MY_COURSES_SUCCESS = 'MY_COURSES_SUCCESS'
export const MY_COURSES_FAIL = 'MY_COURSES_FAIL'
export const MY_COURSES_RESET = 'MY_COURSES_RESET'


export const LIST_COURSES_REQUEST = 'LIST_COURSES_REQUEST'
export const LIST_COURSES_SUCCESS = 'LIST_COURSES_SUCCESS'
export const LIST_COURSES_FAIL = 'LIST_COURSES_FAIL'
export const LIST_COURSES_RESET = 'LIST_COURSES_RESET'

export const LIST_NEW_COURSES_REQUEST = 'LIST_NEW_COURSES_REQUEST'
export const LIST_NEW_COURSES_SUCCESS = 'LIST_NEW_COURSES_SUCCESS'
export const LIST_NEW_COURSES_FAIL = 'LIST_NEW_COURSES_FAIL'
export const LIST_NEW_COURSES_RESET = 'LIST_NEW_COURSES_RESET'


export const LIST_COURSES_POBULAR_REQUEST = 'LIST_COURSES_POBULAR_REQUEST'
export const LIST_COURSES_POBULAR_SUCCESS = 'LIST_COURSES_POBULAR_SUCCESS'
export const LIST_COURSES_POBULAR_FAIL = 'LIST_COURSES_POBULAR_FAIL'
export const LIST_COURSES_POBULAR_RESET = 'LIST_COURSES_POBULAR_RESET'


export const LIST_COURSE_DETAILS_REQUEST = 'LIST_COURSE_DETAILS_REQUEST'
export const LIST_COURSE_DETAILS_SUCCESS = 'LIST_COURSE_DETAILS_SUCCESS'
export const LIST_COURSE_DETAILS_FAIL = 'LIST_COURSE_DETAILS_FAIL'
export const LIST_COURSE_DETAILS_RESET = 'LIST_COURSE_DETAILS_RESET'