export const MY_COURSES_REQUEST = "MY_COURSES_REQUEST";
export const MY_COURSES_SUCCESS = "MY_COURSES_SUCCESS";
export const MY_COURSES_FAIL = "MY_COURSES_FAIL";
export const MY_COURSES_RESET = "MY_COURSES_RESET";

export const ALL_COURSES_REQUEST = "ALL_COURSES_REQUEST";
export const ALL_COURSES_SUCCESS = "ALL_COURSES_SUCCESS";
export const ALL_COURSES_FAIL = "ALL_COURSES_FAIL";
export const ALL_COURSES_RESET = "ALL_COURSES_RESET";

export const LIST_COURSES_REQUEST = "LIST_COURSES_REQUEST";
export const LIST_COURSES_SUCCESS = "LIST_COURSES_SUCCESS";
export const LIST_COURSES_FAIL = "LIST_COURSES_FAIL";
export const LIST_COURSES_RESET = "LIST_COURSES_RESET";

export const GET_SUBCATEGORYS_REQUEST = "GET_SUBCATEGORYS_REQUEST";
export const GET_SUBCATEGORYS_SUCCESS = "GET_SUBCATEGORYS_SUCCESS";
export const GET_SUBCATEGORYS_FAIL = "GET_SUBCATEGORYS_FAIL";
export const GET_SUBCATEGORYS_RESET = "GET_SUBCATEGORYS_RESET";

export const LIST_BYSUBCATEGORYS_REQUEST = "LIST_BYSUBCATEGORYS_REQUEST";
export const LIST_BYSUBCATEGORYS_SUCCESS = "LIST_BYSUBCATEGORYS_SUCCESS";
export const LIST_BYSUBCATEGORYS_FAIL = "LIST_BYSUBCATEGORYS_FAIL";
export const LIST_BYSUBCATEGORYS_RESET = "LIST_BYSUBCATEGORYS_RESET";

export const LIST_NEW_COURSES_REQUEST = "LIST_NEW_COURSES_REQUEST";
export const LIST_NEW_COURSES_SUCCESS = "LIST_NEW_COURSES_SUCCESS";
export const LIST_NEW_COURSES_FAIL = "LIST_NEW_COURSES_FAIL";
export const LIST_NEW_COURSES_RESET = "LIST_NEW_COURSES_RESET";

export const LIST_COURSES_POBULAR_REQUEST = "LIST_COURSES_POBULAR_REQUEST";
export const LIST_COURSES_POBULAR_SUCCESS = "LIST_COURSES_POBULAR_SUCCESS";
export const LIST_COURSES_POBULAR_FAIL = "LIST_COURSES_POBULAR_FAIL";
export const LIST_COURSES_POBULAR_RESET = "LIST_COURSES_POBULAR_RESET";

export const LIST_COURSE_DETAILS_REQUEST = "LIST_COURSE_DETAILS_REQUEST";
export const LIST_COURSE_DETAILS_SUCCESS = "LIST_COURSE_DETAILS_SUCCESS";
export const LIST_COURSE_DETAILS_FAIL = "LIST_COURSE_DETAILS_FAIL";
export const LIST_COURSE_DETAILS_RESET = "LIST_COURSE_DETAILS_RESET";

export const COURSE_UPDATE_REQUEST = "COURSE_UPDATE_REQUEST";
export const COURSE_UPDATE_SUCCESS = "COURSE_UPDATE_SUCCESS";
export const COURSE_UPDATE_FAIL = "COURSE_UPDATE_FAIL";
export const COURSE_UPDATE_RESET = "COURSE_UPDATE_RESET";

export const COURSE_DELETE_REQUEST = "COURSE_DELETE_REQUEST";
export const COURSE_DELETE_SUCCESS = "COURSE_DELETE_SUCCESS";
export const COURSE_DELETE_FAIL = "COURSE_DELETE_FAIL";

export const COURSE_CREATE_REQUEST = "COURSE_CREATE_REQUEST";
export const COURSE_CREATE_SUCCESS = "COURSE_CREATE_SUCCESS";
export const COURSE_CREATE_FAIL = "COURSE_CREATE_FAIL";
export const COURSE_CREATE_RESET = "COURSE_CREATE_RESET";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";

export const CHECK_STUDENT_REQUEST = "CHECK_STUDENT_REQUEST";
export const CHECK_STUDENT_SUCCESS = "CHECK_STUDENT_SUCCESS";
export const CHECK_STUDENT_FAIL = "CHECK_STUDENT_FAIL";
export const CHECK_STUDENT_RESET = "CHECK_STUDENT_RESET";

export const LIST_COURSES_PURCHASED_REQUEST = "LIST_COURSES_PURCHASED_REQUEST";
export const LIST_COURSES_PURCHASED_SUCCESS = "LIST_COURSES_PURCHASED_SUCCESS";
export const LIST_COURSES_PURCHASED_FAIL = "LIST_COURSES_PURCHASED_FAIL";
export const LIST_COURSES_PURCHASED_RESET = "LIST_COURSES_PURCHASED_RESET";

export const LIST_COURSES_SEARCH_REQUEST = "LIST_COURSES_SEARCH_REQUEST";
export const LIST_COURSES_SEARCH_SUCCESS = "LIST_COURSES_SEARCH_SUCCESS";
export const LIST_COURSES_SEARCH_FAIL = "LIST_COURSES_SEARCH_FAIL";
export const LIST_COURSES_SEARCH_RESET = "LIST_COURSES_SEARCH_RESET";

export const GET_CRSRATING_SUCCESS = "GET_CRSRATING_SUCCESS";
export const GET_CRSRATING_REQUEST = "GET_CRSRATING_REQUEST";
export const GET_CRSRATING_FAIL = "GET_CRSRATING_FAIL";
export const GET_CRSRATING_RESET = "GET_CRSRATING_RESET";

export const GET_CRSPRICE_SUCCESS = "GET_CRSPRICE_SUCCESS";
export const GET_CRSPRICE_REQUEST = "GET_CRSPRICE_REQUEST";
export const GET_CRSPRICE_FAIL = "GET_CRSPRICE_FAIL";
export const GET_CRSPRICE_RESET = "GET_CRSPRICE_RESET";
